### ISSUE TITLE
dialog.css transitions obscure sign in with Ubuntu / Firefox 4.0

### ISSUE THREAD

**Issue by humbletim** [mozilla/persona#2169]
Firefox.navigator.buildID 20110419185614
Symptom: The sign in popup dialog appears to stall at "Communicating with Server."  Tested on multiple computers and happens consistently including on http://myfavoritebeer.org.

After some digging seems to be a FF4 issue with CSS -moz-transitions not firing / finishing.  Because, beneath the stalled "Communicating with Server" overlay everything seems fine and manually coercing the transitions allows sign in to proceed normally.

I am working on upgrading client machines to a more modern Firefox (realizing that browserid only officially supports the four current Firefox channels).   But just in case anyone else is dealing with FF4, a reliable workaround is a chrome/userContent.css that effectively disables the transitions:

``` css
html>body section#wait, 
html>body section#error
html>body section#delay {
    -moz-transition-delay: 0s !important;
    -moz-transition-duration: 0s !important;
}
```

... which seem to be set originally in "dialog.css"; probably https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/css/style.css#L177

Regards, -Tim
