### ISSUE TITLE
Persona sign-up page's placeholder input texts same font as regular input

### ISSUE THREAD

**Issue by peterbe** [mozilla/persona#2187]
This screenshot demonstrates how the placeholder texts appear just like regular input texts. The placeholder texts should be faint degree of grey or something. At the moment I'm just not sure if it's my text or the default text in there. 
http://cl.ly/IQ7o

**Comment by peterbe** [comment]
The CSS has :

``` css
input[type="text"], input[type="email"], input[type="password"] { 
     color: rgb(56, 56, 56);
     ...
}
```

Removing that color spec will solve the problem but then that's maybe not the color you want for when text is filled in.
