### ISSUE TITLE
border-radius is defined twice in the signIn/signOut selector in browserid.css

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3814]
https://static.login.persona.org/v/2543e40425/production/en/browserid.css

Lines 1110-1116 of browserid.css (Firefox pretty-prints up the CSS) has the following sauce:

``` css
header a.signIn,header a.signOut{
    border-radius:6px;
    padding:6px 20px;
    border-radius:7px;
    border:1px solid #333;
    box-shadow:0 0 1px #777
}
```
